=== 3etechinns/accounter/setup/tar/config/demo.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT vote EMPTY>
<!ATTLIST vote
	choice CDATA #IMPLIED
	id CDATA #IMPLIED
>
<!ELEMENT topic ((attachment*))>
<!ATTLIST topic
	isResponse CDATA  "false"
	parentId CDATA #IMPLIED
	status CDATA  "1"
	subject CDATA #REQUIRED
	topicID CDATA #IMPLIED
>
<!ELEMENT tool ((address* | event* | file* | sharedfile* | link* | message* | note* | page* | picture* | poll* | restorePoint* | table* | task* | topic*))>
<!ATTLIST tool
	browseTogether CDATA #IMPLIED
	createdDate CDATA #REQUIRED
	creator CDATA #REQUIRED
	description CDATA #REQUIRED
	hideFavorite CDATA  #IMPLIED
	lastModifiedDate CDATA #REQUIRED
	lastModifier CDATA #REQUIRED
	lastModifierDevice CDATA #REQUIRED  
	name CDATA #REQUIRED
	navigateLocation CDATA #IMPLIED
	title CDATA  #IMPLIED
	toolID CDATA #REQUIRED
>
<!ELEMENT task ((attachment, subtask)*)>
<!ATTLIST task
	actualStartDate CDATA #REQUIRED
	assignTo CDATA #REQUIRED
	description CDATA #REQUIRED
	duration CDATA #REQUIRED
	finishDate CDATA #REQUIRED
	name CDATA #REQUIRED
	predecessorNameList CDATA #REQUIRED
	priority CDATA  #REQUIRED
	startDate  CDATA #REQUIRED
	status CDATA  #REQUIRED
	taskid  CDATA #REQUIRED
>
<!ELEMENT table ((column+, record*))>
<!ATTLIST table
	name CDATA #REQUIRED
	tableId CDATA #REQUIRED
>
<!ELEMENT subtask EMPTY>
<!ATTLIST subtask
	taskid CDATA #REQUIRED
>
<!ELEMENT role EMPTY>
<!ATTLIST role
	description CDATA #IMPLIED
	displayName (Participant | Manager | Guest) #IMPLIED
	name (ISpace.Participant | ISpace.Manager | ISpace.Guest) #REQUIRED
>
<!ELEMENT revision (#PCDATA)>
<!ATTLIST revision
	lastModifiedDate CDATA #REQUIRED
	lastModifier CDATA #REQUIRED
	name CDATA #REQUIRED
	version CDATA #REQUIRED
>
<!ELEMENT restorePoint (#PCDATA)>
<!ATTLIST restorePoint
	name CDATA #REQUIRED
	restorePointID CDATA #REQUIRED
	size CDATA #REQUIRED
	status CDATA  #REQUIRED
>
<!ELEMENT reminder EMPTY>
<!ATTLIST reminder
	duration  CDATA #REQUIRED
	remiderType CDATA #REQUIRED
	type CDATA #REQUIRED
>
<!ELEMENT record ((column*))>
<!ATTLIST record
	id  CDATA #REQUIRED
>
<!ELEMENT property (#PCDATA)>
<!ELEMENT poll ((choice+, vote*))>
<!ATTLIST poll
	closePollManually CDATA  #REQUIRED
	multipleChoice CDATA   #REQUIRED
	pollId CDATA  #REQUIRED
	pollQuestion CDATA #REQUIRED
	pollStatus CDATA   #REQUIRED
	sendResultsToAll CDATA   #REQUIRED
	showResultsImmediately CDATA   #REQUIRED
	showVoterID CDATA   #REQUIRED
>
<!ELEMENT picture ((attachment))>
<!ATTLIST picture
	description CDATA  #REQUIRED
	fileName CDATA  #REQUIRED
	fileState CDATA   #REQUIRED
	picturId CDATA  #REQUIRED
>
<!ELEMENT photo EMPTY>
<!ATTLIST photo
	filename CDATA  #REQUIRED
	flag CDATA   #REQUIRED
	id CDATA  #REQUIRED
	isCompressed CDATA   #REQUIRED
	isEncrypted CDATA   #REQUIRED
	size CDATA #REQUIRED 
>
<!ELEMENT permission (#PCDATA)>
<!ATTLIST permission
	displayName CDATA #REQUIRED
	name (PERMISSION_INVITE_MEMBER | PERMISSION_DELETE_TOOL | PERMISSION_DELETE_SPACE_FROM_SYSTEM | PERMISSION_DELETE_SPACE_FROM_NETWORK | PERMISSION_DELETE_MEMBER | PERMISSION_CHANGE_SPACE | PERMISSION_ADD_TOOL) #REQUIRED
>
<!ELEMENT page ((attachment*, content?))>
<!ATTLIST page
	name CDATA  #REQUIRED
	pageID CDATA  #REQUIRED
	path CDATA  #REQUIRED
	version CDATA  #REQUIRED
>
<!ELEMENT note ((attachment*, revision*))>
<!ATTLIST note
	name CDATA   #REQUIRED
	noteId CDATA   #REQUIRED
	version CDATA   #REQUIRED
>
<!ELEMENT message (#PCDATA)>
<!ATTLIST message
	date CDATA  #REQUIRED
	from CDATA  #REQUIRED
	id CDATA  #REQUIRED
>
<!ELEMENT link (#PCDATA)>
<!ATTLIST link
	linkId CDATA #REQUIRED
	title CDATA #REQUIRED
>
<!ELEMENT file ((attachment?))>
<!ATTLIST file
	count CDATA #REQUIRED
	fileID CDATA #REQUIRED
	fileName CDATA #REQUIRED
	path CDATA #REQUIRED
	size CDATA #REQUIRED
	version CDATA  #REQUIRED
>
<!ELEMENT sharedfile ((attachment?))>
<!ATTLIST sharedfile
	creator CDATA #REQUIRED
	fileID CDATA #REQUIRED
	fileName CDATA #REQUIRED
	lastModifiedDate CDATA #REQUIRED
	lastModifier CDATA #REQUIRED
	lastModifierDevice CDATA #REQUIRED
	path CDATA #REQUIRED
	size CDATA #REQUIRED
	version CDATA  #REQUIRED
>
<!ELEMENT event ((reminder*))>
<!ATTLIST event
	alldayEvent CDATA #REQUIRED
	description CDATA #REQUIRED
	eDate CDATA #REQUIRED
	eventAccessType CDATA  #REQUIRED
	eventId CDATA #REQUIRED
	location CDATA #REQUIRED
	repeatEndDate CDATA #REQUIRED
	repeatFrequency CDATA #REQUIRED
	repeatMonthBy CDATA #REQUIRED
	repeatType CDATA #REQUIRED
	repeatWeeklyOn CDATA  #REQUIRED
	sDate CDATA #REQUIRED
	subject CDATA #REQUIRED
>
<!ELEMENT content EMPTY>
<!ATTLIST content
	lastModifiedDate CDATA #REQUIRED
	lastModifier CDATA #REQUIRED
	name CDATA #REQUIRED
	version CDATA  #REQUIRED
>
<!ELEMENT column (#PCDATA)>
<!ELEMENT choice (#PCDATA)>
<!ELEMENT attachment EMPTY>
<!ATTLIST attachment
	filename CDATA #REQUIRED
	flag CDATA #REQUIRED
	id CDATA #REQUIRED
	isCompressed CDATA #REQUIRED
	isEncrypted CDATA #REQUIRED
	size CDATA #REQUIRED
>
<!ELEMENT member ((role+))>
<!ATTLIST member
	contact CDATA #REQUIRED
	id CDATA #REQUIRED
>
<!ELEMENT address ((property*, photo?))>
<!ATTLIST address
	addressId CDATA #REQUIRED
>
<!ELEMENT CREATE_WORKSPACE ((role+, tool*, member*, permission+))>
<!ATTLIST CREATE_WORKSPACE
	createdDate CDATA #REQUIRED
	creator CDATA #REQUIRED
	description CDATA #REQUIRED
	name CDATA #REQUIRED
	spaceId CDATA #REQUIRED
>

=== 3etechinns/accounter/setup/tar/config/demo.xml
<!DOCTYPE CREATE_WORKSPACE SYSTEM "demo.dtd">
<CREATE_WORKSPACE name="importTest2"
	creator="50zbzq4kslcwk73xde6sv8i2yd1c4grekqxz3uc8" description="sdfgdfg"
	spaceId="rjd89st4sar2mlm726z744fcduhazzmgj9ckz4ma" createdDate="2009-04-10 10:10:00.105">
	<role name="ISpace.Manager" displayName="Manager"
		description="Usually have all available permissions" />
	<role name="ISpace.Participant" displayName="Participant"
		description="Can usually invite new members and add new tools" />
	<role name="ISpace.Guest" displayName="Guest"
		description="Permissions usually restricted to read-only activities" />
	<tool name="Backup Tool" description="Select tool from the list below."
		toolID="43vj0q4t648zpk3f7meho3svpqtb7c35hf53cw3w" creator="50zbzq4kslcwk73xde6sv8i2yd1c4grekqxz3uc8"
		createdDate="2009-04-15 11:02:19.276" lastModifiedDate="2009-04-15 11:02:44.899"
		lastModifier="50zbzq4kslcwk73xde6sv8i2yd1c4grekqxz3uc8"
		templateID ="BackupTool"
		lastModifierDevice="0">
		<restorePoint restorePointID="xj7rby3gwqphu2doeo279q7hxyraf7e4wvwri63b"
			name="point1" size="0" status="0">afsfsd</restorePoint>
		<restorePoint restorePointID="kw6fvk1ru3wlk798b6xl56lakh3gkmwzv706g2ro"
			name="point2" size="0" status="0">fdghdfgfg</restorePoint>
	</tool>
	<tool name="ChatTool" description="Description"
		toolID="i06bkznd4jjvbatzpvinglexidir46llt1ew0o0s" creator="50zbzq4kslcwk73xde6sv8i2yd1c4grekqxz3uc8"
		createdDate="2009-04-15 11:03:07.754" lastModifiedDate="2009-04-15 11:04:20.261"
		lastModifier="50zbzq4kslcwk73xde6sv8i2yd1c4grekqxz3uc8"
		templateID ="ChatTool"
		lastModifierDevice="0">
		<message date="2009-04-15 11:03:09.918" from="50zbzq4kslcwk73xde6sv8i2yd1c4grekqxz3uc8"
			id="hqw4ze9i7twlzoyyp30uuiq53424q8qf64dfhjjz">hi</message>
		<message date="2009-04-15 11:04:20.26" from="50zbzq4kslcwk73xde6sv8i2yd1c4grekqxz3uc8"
			id="awrvdjcld0xdmmqs290gpt84nsgexfyt1rl3yvs2">how r u buddy</message>
	</tool>
	<tool name="NotepadTool" description="Select tool from the list"
		toolID="dn9qn9zf44c17tlqailnplni0vunlxkscskp8y9m" creator="50zbzq4kslcwk73xde6sv8i2yd1c4grekqxz3uc8"
		createdDate="2009-04-15 12:21:56.729" lastModifiedDate="2009-04-15 12:49:40.321"
		lastModifier="50zbzq4kslcwk73xde6sv8i2yd1c4grekqxz3uc8"
		templateID ="NotepadTool"
		lastModifierDevice="0">
		<note name="mynote" noteId="teqnn1t5vzj2rwet9jyn7fi6l61vcpo4slxmcawt"
			version="2">
			<attachment filename="teqnn1t5vzj2rwet9jyn7fi6l61vcpo4slxmcawt"
				id="u4d1g5goizhem1qsxe57oirnjkwy5tn6fhxdkze4" size="32" flag="1"
				isCompressed="false" isEncrypted="false" />
			<revision name="mynote" lastModifiedDate="2009-04-15 12:28:18.577"
				lastModifier="50zbzq4kslcwk73xde6sv8i2yd1c4grekqxz3uc8" version="0">
				Note content has modified</revision>
			<revision name="mynote" lastModifiedDate="2009-04-15 12:32:36.356"
				lastModifier="50zbzq4kslcwk73xde6sv8i2yd1c4grekqxz3uc8" version="1">
				Note content has modified</revision>
		</note>
	</tool>
	<tool name="DiscussionTool" description="Select tool from the list"
		toolID="b894av3tpj1hc3y01jub4855xosil575crq2zmcn" creator="50zbzq4kslcwk73xde6sv8i2yd1c4grekqxz3uc8"
		createdDate="2009-04-15 14:21:38.115" lastModifiedDate="2009-04-15 14:33:02.341"
		lastModifier="50zbzq4kslcwk73xde6sv8i2yd1c4grekqxz3uc8"
		templateID ="DiscussionTool"
		lastModifierDevice="0">
		<topic isResponse="false" status="1" subject="voting"
			topicID="0kkmgwsr2hkilz6gncaut7t16chgpnvphh0eetrd">
			<attachment filename="0kkmgwsr2hkilz6gncaut7t16chgpnvphh0eetrd"
				id="vv746ekjqmu6vpozzzmu1f1n5pdcpvve5rrxtps2" size="42" flag="0"
				isCompressed="false" isEncrypted="false" />
			<attachment filename="demo.xml"
				id="m1x6o07aaabxhkk7bq0gvu1s6ta6dnnn193ximo8" size="3815" flag="0"
				isCompressed="false" isEncrypted="false" />
		</topic>
		<topic isResponse="false" parentId="0kkmgwsr2hkilz6gncaut7t16chgpnvphh0eetrd"
			status="1" subject="Re: voting" topicID="a1rb04ugibzmzem1uztqq8i1l7e2a6ccxoqh6f0h">
			<attachment filename="a1rb04ugibzmzem1uztqq8i1l7e2a6ccxoqh6f0h"
				id="o607nu6et9gabt0v4jf7ix0mjh35d75opg87al01" size="16" flag="0"
				isCompressed="false" isEncrypted="false" />
		</topic>
	</tool>
	<tool name="Wiki Tool" description="Select tool from the list"
		toolID="2hvvubofkfuzxj0ukfbnldtauy3cn6bvua11u5yk" creator="50zbzq4kslcwk73xde6sv8i2yd1c4grekqxz3uc8"
		createdDate="2009-04-15 14:36:40.94" lastModifiedDate="2009-04-15 14:37:16.651"
		lastModifier="50zbzq4kslcwk73xde6sv8i2yd1c4grekqxz3uc8"
		templateID ="WikiTool"
		lastModifierDevice="0">
		<page name="homepage" pageID="0000000000000000000000000000000000000000"
			version="0" path="">
			<attachment filename="rootPage"
				id="zeazfh9zhfiggxg0n79rrxpchu41udw1wx8t4ktq" size="104" flag="1"
				isCompressed="false" isEncrypted="false" />
		</page>
		<page name="testwiki" pageID="dlb52fipmn350ibofkdbva6w1bc95bc5uvsrya83"
			version="1" path="/homepage">
			<attachment filename="dlb52fipmn350ibofkdbva6w1bc95bc5uvsrya83"
				id="astc2s6arcgtxwl6hupi9pskeg250y91g0y3h859" size="19" flag="1"
				isCompressed="false" isEncrypted="false" />
			<content lastModifiedDate="2009-04-15 14:36:54.16"
				lastModifier="50zbzq4kslcwk73xde6sv8i2yd1c4grekqxz3uc8" name="testwiki"
				version="0" />
		</page>
		<page name="hello" pageID="7vzjid6axch1x1uxa75q7f3441caylbbmzus47ht"
			version="1" path="/homepage/testwiki">
			<attachment filename="7vzjid6axch1x1uxa75q7f3441caylbbmzus47ht"
				id="c1bgvkoynmeqtmsnj0r8bx2vqbclw0ek093ev4mw" size="0" flag="1"
				isCompressed="false" isEncrypted="false" />
			<content lastModifiedDate="2009-04-15 14:37:14.773"
				lastModifier="50zbzq4kslcwk73xde6sv8i2yd1c4grekqxz3uc8" name="hello"
				version="0" />
		</page>
		<page name="homepage" pageID="0000000000000000000000000000000000000000"
			version="0" path="">
			<attachment filename="rootPage"
				id="zeazfh9zhfiggxg0n79rrxpchu41udw1wx8t4ktq" size="104" flag="1"
				isCompressed="false" isEncrypted="false" />
		</page>
	</tool>
	<tool name="TaskTool" description="Select tool from the list"
		toolID="xrsgz05elwamsis6zngwj02kwnjsmxo5t46z4odo" creator="50zbzq4kslcwk73xde6sv8i2yd1c4grekqxz3uc8"
		createdDate="2009-04-15 14:42:50.09" lastModifiedDate="2009-04-15 14:44:12.154"
		lastModifier="50zbzq4kslcwk73xde6sv8i2yd1c4grekqxz3uc8"
		templateID ="TaskTool"
		lastModifierDevice="0">
		<task taskid="0000000000000000000000000000000000000000" name="test"
			description="sdfgdfg" assignTo="50zbzq4kslcwk73xde6sv8i2yd1c4grekqxz3uc8"
			startDate="2009-04-15 14:43:34.572" finishDate="2009-04-17 00:00:00.0"
			duration="1" priority="1" predecessorNameList=""
			actualStartDate="2009-04-10 10:10:00.105" status="5">
			<attachment filename="viewsrc.html"
				id="jswdh2s8aal9v9rsh54z5kvbnz8xdjrmu7s9eorv" size="78" flag="0"
				isCompressed="false" isEncrypted="false" />
			<subtask taskid="n329m4dtj6b9c8166mjsugfncx4py0487hen34ck" />
		</task>
		<task taskid="n329m4dtj6b9c8166mjsugfncx4py0487hen34ck" name="new"
			description="" assignTo="50zbzq4kslcwk73xde6sv8i2yd1c4grekqxz3uc8"
			startDate="2009-04-16 00:00:00.0" finishDate="2009-04-17 00:00:00.0"
			duration="1" priority="1" predecessorNameList="" actualStartDate="2009-04-16 00:00:00.0"
			status="5" />
	</tool>
	<tool name="PollsTool" description="Select tool from the list"
		toolID="une4m4n0re0ih46j6eclpnxg5gzhiiaoj4g9k3jz" creator="50zbzq4kslcwk73xde6sv8i2yd1c4grekqxz3uc8"
		createdDate="2009-04-15 15:16:39.491" lastModifiedDate="2009-04-15 15:34:00.579"
		lastModifier="50zbzq4kslcwk73xde6sv8i2yd1c4grekqxz3uc8"
		templateID ="PollsTool"
		lastModifierDevice="0">
		<poll pollId="ul2qv747umnc9n95r4rgljbro0jclx78wh5o29fq"
			pollQuestion="prime minister" closePollManually="true" pollStatus="true"
			multipleChoice="false" sendResultsToAll="true"
			showResultsImmediately="true" showVoterID="false">
			<choice>man mohan</choice>
			<choice>soniya</choice>
			<choice>advani</choice>
			<choice>modhi</choice>
			<vote id="50zbzq4kslcwk73xde6sv8i2yd1c4grekqxz3uc8" choice="2" />
		</poll>
	</tool>
	<tool name="PictureTool" description="Select tool from the list"
		toolID="5vhzhjz9n7s8jdfth1pn1ada23ayjopgp7itxqyw" creator="50zbzq4kslcwk73xde6sv8i2yd1c4grekqxz3uc8"
		createdDate="2009-04-15 15:34:14.093" lastModifiedDate="2009-04-15 15:34:33.374"
		lastModifier="50zbzq4kslcwk73xde6sv8i2yd1c4grekqxz3uc8"
		templateID ="PictureTool"
		lastModifierDevice="0">
		<picture description="" fileName="earthquake.jpg" fileState="false"
			picturId="i0pc2sozeodu1g6w3lisxjmy73lyghu8zovsvn3u">
			<attachment filename="earthquake.jpg"
				id="jqfepdph3c3b5j6bd59bth6mqivoir4bk902m32r" size="68761" flag="0"
				isCompressed="false" isEncrypted="false" />
		</picture>
	</tool>
	<tool name="WebLinksTool" description="Select tool from the list"
		toolID="6krr8emu02ollaj1rsqwr5r8iolqnrdqpymey9pw" creator="50zbzq4kslcwk73xde6sv8i2yd1c4grekqxz3uc8"
		createdDate="2009-04-15 15:39:23.783" lastModifiedDate="2009-04-15 15:39:48.804"
		lastModifier="50zbzq4kslcwk73xde6sv8i2yd1c4grekqxz3uc8"
		templateID ="WebLinksTool"
		lastModifierDevice="0" title="" navigateLocation="about:blank"
		browseTogether="false" hideFavorite="true">
		<link linkId="5janv5t3vvujryfpdv94vxvk0rhmb9cxftgeqn5y" title="yahoo">
			yahoo.com</link>
	</tool>
	<tool name="CalendarTool" description="Select tool from the list"
		toolID="ixk56jtrmkx12qijmijzn5h28zbzlu8ir2bntn2q" creator="50zbzq4kslcwk73xde6sv8i2yd1c4grekqxz3uc8"
		createdDate="2009-04-15 15:53:37.534" lastModifiedDate="2009-04-15 15:54:23.496"
		lastModifier="50zbzq4kslcwk73xde6sv8i2yd1c4grekqxz3uc8"
		templateID ="CalenderTool"
		lastModifierDevice="0">
		<event sDate="2009-04-16 00:00:00.0" subject="election"
			description="hhhh" alldayEvent="false" eDate="2009-04-16 00:15:00.0"
			eventAccessType="1" eventId="lkvt711nnj76jx3bpgm6i8f5i0v6r0fwp48i31kk"
			location="ffhd" repeatEndDate="2009-04-16 00:15:00.0" repeatFrequency="1" repeatMonthBy="0"
			repeatType="6" repeatWeeklyOn="0">
			<reminder type="0" duration="10" remiderType="0" />
		</event>
	</tool>
